#----------------------
#  GitHub Action File
#----------------------

name: Build

on: 
  push:
    branches: main

jobs: 
  testing: 
    runs-on: ubuntu-latest

    steps: 
      - name: Building
        run : |
            echo "Hello World from Test"
            uname -a
            pwd
            ls -latr


  deploy:
    runs-on: [ubuntu-latest]
    needs: [testing]

    steps:
      - name: Deployment
        run : echo "Hello World from Deploy"
