#----------------------
#  GitHub Action File
#----------------------

name: Build

on: 
  push:
    branches: main

jobs: 
  testing: 
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Building
        run : |
            echo "Hello World from Test"
            uname -a
            pwd
            ls -latr


  deploy:
    runs-on: [ubuntu-latest]
    needs: [testing]

    steps:
      - name: Deployment
        run : echo "Hello World from Deploy"

      - uses: actions/checkout@v3
        name: Check out code

      - uses: mr-smithers-excellent/docker-build-push@v6
        name: Build & push Docker image
        with:
          image: jpummill/actions_test2
          tags: v2, latest
          registry: docker.io
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
