#----------------------
#  GitHub Action File
#----------------------

name: Build

on: 
  push:
    branches: master

jobs: 
  testing: 
    runs-on: [ubuntu-latest]

    steps: 
      - name: Building
        run : echo "Hello World from Test"

  deploy:
    runs-on: [ubuntu-latest]
    needs: [testing]

    steps:
      - name: Deployment
        run : echo "Hello World from Deploy"
