#----------------------
#  GitHub Action File
#----------------------

name: Build

on: [push]

jobs: 
  testing: 
    runs-on: [ubuntu-latest]

    steps: 
      - name: Pring Nice Message
        run : echo "Hello World from Test"

    
